USE [master]
GO

/****** Object:  Database [PostBD]    Script Date: 9/9/2021 8:44:02 PM ******/
CREATE DATABASE [PostBD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PostBD', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\PostBD.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'PostBD_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\PostBD_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PostBD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PostBD] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PostBD] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PostBD] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PostBD] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PostBD] SET ARITHABORT OFF 
GO

ALTER DATABASE [PostBD] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PostBD] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PostBD] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PostBD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PostBD] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PostBD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PostBD] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PostBD] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PostBD] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PostBD] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PostBD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PostBD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PostBD] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PostBD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PostBD] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PostBD] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PostBD] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PostBD] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PostBD] SET  MULTI_USER 
GO

ALTER DATABASE [PostBD] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PostBD] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PostBD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PostBD] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [PostBD] SET  READ_WRITE 
GO


